cursor #f0dfd8
cursor_text_color #d7c2b9

foreground            #f0dfd8
background            #1a120e
selection_foreground  #432b1e
selection_background  #e6beab
url_color             #ffb690

# black
color8   #262626
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green
color2   #8aac8b
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #8f8aac
color4  #ffb690
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #c49ec4

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
