bind = Super, S, exec, spotify

# Change the size of active window
bind = Ctrl+Shift, left, resizeactive, -10 0
bind = Ctrl+Shift, right, resizeactive, 10 0
bind = Ctrl+Shift, up, resizeactive, 0 -10
bind = Ctrl+Shift, down, resizeactive, 10 0
